In [12]:
import numpy as np
# Tao mang
a = np.array([1,2,3])
print(a)
# In ra 1 phan tu
element = a[1]
print(element)

[1 2 3]
2


In [18]:
# Tao mang 2 chieu
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Matrix:")
print (matrix)
# In mot phan tu
element= matrix[1,2]
print(element)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [ ]:
#Cach tao mang
#